syntax = "proto3";
package grpc;

message StreamEvent {
    oneof event {
        bytes data = 1;
        bool eof = 2;
        string error = 3;
    }
}

message Command {
    repeated string args = 1;
}

message ExecCommandRequest {
    oneof input {
        Command cmd = 1;
        StreamEvent stdin = 2;
    }
}

message ExecCommandResponse {
    oneof output {
        StreamEvent stdout = 1;
        StreamEvent stderr = 2;
        int32 exit_code = 3;
    }
}

service ExecNoninteractiveService {
    rpc RunCommand(stream ExecCommandRequest) returns (stream ExecCommandResponse);
}
